version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8019:80
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads
      - ./upgrade:/var/www/html/wp-content/upgrade
      - ./plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_NAME: scaleupdb
      WORDPRESS_DB_PASSWORD: root

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3319:3306
    environment:
      MYSQL_ROOT_PASSWORD: root